
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkujzgjuqzywgzjqxavp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdWp6Z2p1cXp5d2d6anF4YXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5Mzk1NjYsImV4cCI6MjA1OTUxNTU2Nn0.jn-4d0YpRS7VZZAQRQSKi_-wxLAIxTq8mUOkLY4PNa8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage
  }
});
