
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgkugvcuzyxsxutvtdcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBna3VndmN1enl4c3h1dHZ0ZGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NTU5MzcsImV4cCI6MjA2MjMzMTkzN30.KIDh3kNpnsWncffEK-bWvhlXBbrV85rNeBjuUV8cvvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storage: localStorage,
      detectSessionInUrl: true,
      flowType: 'pkce'
    }
  }
);
